local gorgets = T{};

gorgets.Flame = T{'Arching Arrow', 'Ascetic\'s Fury', 'Asuran Fists', 'Atonement', 'Blade: Shun', 'Burning Blade', 'Decimation', 'Detonator', 'Drakesbane', 'Dulling Arrow', 'Empyreal Arrow', 'Final Heaven', 'Flaming Arrow', 'Full Swing', 'Garland of Bliss', 'Heavy Shot', 'Hexa Strike', 'Hot Shot', 'Insurgency', 'Knights of Round', 'Last Stand', 'Mandalic Stab', 'Mistral Axe', 'Metatron Torment', 'Realmrazer', 'Red Lotus Blade', 'Scourge', 'Shijin Spiral', 'Sniper Shot', 'Spinning Attack', 'Spinning Axe', 'Stringing Pummel', 'Tachi: Kagero', 'Tachi: Kasha', 'Upheaval', 'Wheeling Thrust'};

gorgets.Soil = T{'Aeolian Edge', 'Asuran Fists', 'Avalanche Axe', 'Blade: Ei', 'Blade: Ku', 'Blade: Retsu', 'Blade: Ten', 'Calamity', 'Catastrophe', 'Crescent Moon', 'Dancing Edge', 'Entropy', 'Evisceration', 'Exenterator', 'Expiacion', 'Fast Blade', 'Hard Slash', 'Impulse Drive', 'Iron Tempest', 'King\'s Justice', 'Leaden Salute', 'Mercy Stroke', 'Nightmare Scythe', 'Omniscience', 'Primal Rend', 'Pyrrhic Kleos', 'Rampage', 'Requiescat', 'Resolution', 'Retribution', 'Savage Blade', 'Seraph Blade', 'Shattersoul', 'Shining Blade', 'Sickle Moon', 'Slice', 'Spinning Axe', 'Spinning Scythe', 'Spiral Hell', 'Stardiver', 'Stringing Pummel', 'Sturmwind', 'Swift Blade', 'Tachi: Enpi', 'Tachi: Jinpu', 'Tachi: Rana', 'Trueflight', 'Viper Bite', 'Vorpal Blade', 'Vorpal Scythe', 'Wasp Sting'};

gorgets.Aqua = T{'Atonement', 'Blade: Teki', 'Brainshaker', 'Circle Blade', 'Cross Reaper', 'Dark Harvest', 'Entropy', 'Quietus', 'Death Blossom', 'Decimation', 'Expiacion', 'Full Break', 'Garland of Bliss', 'Gate of Tartarus', 'Geirskogul', 'Ground Strike', 'Last Stand', 'Mordant Rime', 'Namas Arrow', 'Piercing Arrow', 'Pyrrhic Kleos', 'Rudra\'s Storm', 'Primal Rend', 'Raging Rush', 'Retribution', 'Ruinator', 'Shadow of Death', 'Shadowstitch', 'Shockwave', 'Shoulder Tackle', 'Sidewinder', 'Skullbreaker', 'Slug Shot', 'Smash Axe', 'Spinning Scythe', 'Spiral Hell', 'Split Shot', 'Starburst', 'Steel Cyclone', 'Sturmwind', 'Sunburst', 'Tachi: Gekko', 'Tachi: Koki', 'Vidohunir', 'Vorpal Thrust'};

gorgets.Breeze = T{'Aeolian Edge', 'Backhand Blow', 'Black Halo', 'Blade: Jin', 'Blade: Kamu', 'Blade: Metsu', 'Blade: To', 'Camlann\'s Torment', 'Coronach', 'Cyclone', 'Dancing Edge', 'Death Blossom', 'Dragon Kick', 'Earth Crusher', 'Exenterator', 'Freezebite', 'Gale Axe', 'Ground Strike', 'Gust Slash', 'King\'s Justice', 'Mordant Rime', 'Raging Axe', 'Randgrith', 'Red Lotus Blade', 'Resolution', 'Ruinator', 'Savage Blade', 'Shark Bite', 'Shell Crusher', 'Sidewinder', 'Slug Shot', 'Spinning Slash', 'Steel Cyclone', 'Tachi: Jinpu', 'Tachi: Kaiten', 'Tachi: Shoha', 'Tachi: Yukikaze', 'Tornado Kick', 'Trueflight', 'True Strike', 'Victory Smite', 'Vidohunir'};

gorgets.Snow = T{'Blade: To', 'Blast Arrow', 'Blast Shot', 'Cross Reaper', 'Death Blossom', 'Expiacion', 'Freezebite', 'Frostbite', 'Full Break', 'Gate of Tartarus', 'Geirskogul', 'Ground Strike', 'Guillotine', 'Quietus', 'Impulse Drive', 'Mordant Rime', 'Namas Arrow', 'Piercing Arrow', 'Pyrrhic Kleos', 'Rudra\'s Storm', 'Ruinator', 'Raging Rush', 'Shadow of Death', 'Shattersoul', 'Skullbreaker', 'Smash Axe', 'Spiral Hell', 'Steel Cyclone', 'Tachi: Gekko', 'Tachi: Hobaku', 'Tachi: Rana', 'Tachi: Yukikaze', 'Tornado Kick', 'Vidohunir'};

gorgets.Thunder = T{'Aeolian Edge', 'Apex Arrow', 'Armor Break', 'Avalanche Axe', 'Black Halo', 'Blade: Chi', 'Blade: Jin', 'Blade: Kamu', 'Blade: Shun', 'Calamity', 'Camlann\'s Torment', 'Circle Blade', 'Combo', 'Cyclone', 'Death Blossom', 'Dragon Kick', 'Earth Crusher', 'Exenterator', 'Flat Blade', 'Full Swing', 'Ground Strike', 'Heavy Swing', 'Howling Fist', 'Judgment', 'King\'s Justice', 'Leg Sweep', 'Mordant Rime', 'Raging Axe', 'Raging Fists', 'Raiden Thrust', 'Realmrazer', 'Resolution', 'Rock Crusher', 'Savage Blade', 'Seraph Strike', 'Shark Bite', 'Shield Break', 'Shining Strike', 'Shoulder Tackle', 'Sickle Moon', 'Skewer', 'Spinning Attack', 'Spinning Axe', 'Spinning Slash', 'Tachi: Goten', 'Tachi: Koki', 'Tachi: Shoha', 'Thunder Thrust', 'Tornado Kick', 'Trueflight', 'True Strike', 'Victory Smite', 'Vidohunir', 'Vorpal Blade', 'Weapon Break'};

gorgets.Light = T{'Apex Arrow', 'Arching Arrow', 'Ascetic\'s Fury', 'Atonement', 'Blade: Chi', 'Blade: Ku', 'Blade: Rin', 'Blade: Shun', 'Blast Arrow', 'Blast Shot', 'Camlann\'s Torment', 'Decimation', 'Detonator', 'Double Thrust', 'Drakesbane', 'Dulling Arrow', 'Empyreal Arrow', 'Evisceration', 'Final Heaven', 'Flaming Arrow', 'Garland of Bliss', 'Heavy Shot', 'Hexa Strike', 'Hot Shot', 'Howling Fist', 'Insurgency', 'Knights of Round', 'Leaden Salute', 'Last Stand', 'Mandalic Stab', 'Metatron Torment', 'Mistral Axe', 'Omniscience', 'Piercing Arrow', 'Power Slash', 'Realmrazer', 'Raiden Thrust', 'Scourge', 'Shijin Spiral', 'Sidewinder', 'Skewer', 'Slug Shot', 'Sniper Shot', 'Split Shot', 'Stardiver', 'Tachi: Enpi', 'Tachi: Goten', 'Tachi: Kasha', 'Thunder Thrust', 'Torcleaver', 'Victory Smite', 'Upheaval', 'Vorpal Scythe', 'Vorpal Thrust', 'Wheeling Thrust'};

gorgets.Shadow = T{'Asuran Fists', 'Black Halo', 'Blade: Ei', 'Blade: Hi', 'Blade: Kamu', 'Blade: Ku', 'Blade: Ten', 'Catastrophe', 'Quietus', 'Entropy', 'Evisceration', 'Impulse Drive', 'Insurgency', 'Keen Edge', 'Leaden Salute', 'Mandalic Stab', 'Mercy Stroke', 'Requiescat', 'Rudra\'s Storm', 'Nightmare Scythe', 'Omniscience', 'One Inch Punch', 'Penta Thrust', 'Primal Rend', 'Retribution', 'Shattersoul', 'Starburst', 'Stardiver', 'Stringing Pummel', 'Sunburst', 'Swift Blade', 'Tachi: Kasha', 'Tachi: Rana', 'Tachi: Shoha', 'Upheaval'};

return gorgets;